// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DP_ZoomController","status":true,"description":"マップの拡大率を制御します。v0.31 beta20160116","parameters":{"Base Scale":"2","Encount Effect":"true"}}
];
